# Generated by Django 5.0.6 on 2024-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalappenums',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical app enums', 'verbose_name_plural': 'historical app enumss'},
        ),
        migrations.AlterModelOptions(
            name='historicalappsettings',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical app settings', 'verbose_name_plural': 'historical app settingss'},
        ),
        migrations.AlterModelOptions(
            name='historicalstore',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical store', 'verbose_name_plural': 'historical Stores'},
        ),
        migrations.AlterField(
            model_name='historicalappenums',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalappsettings',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstore',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
