# Generated by Django 5.0.6 on 2024-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalasset',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical asset', 'verbose_name_plural': 'historical Assets'},
        ),
        migrations.AlterModelOptions(
            name='historicalassetcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical asset category', 'verbose_name_plural': 'historical Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='historicalassetlocation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical asset location', 'verbose_name_plural': 'historical asset locations'},
        ),
        migrations.AlterModelOptions(
            name='historicalassetserialnumber',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical asset serial number', 'verbose_name_plural': 'historical asset serial numbers'},
        ),
        migrations.AlterModelOptions(
            name='historicalassetsubcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical asset subcategory', 'verbose_name_plural': 'historical Asset Subcategories'},
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetcategory',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetlocation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetserialnumber',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalassetsubcategory',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
