# Generated by Django 4.1.2 on 2024-05-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('db_name', models.CharField(max_length=50, unique=True)),
                ('domain_name', models.CharField(max_length=50, unique=True)),
                ('business_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('business_code', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('vat_tax_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(db_index=True, max_length=12)),
                ('business_logo', models.ImageField(upload_to='images/')),
                ('business_details', models.JSONField(blank=True, null=True)),
                ('business_address', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('business_category', models.CharField(db_index=True, max_length=255)),
                ('business_description', models.TextField()),
                ('upload_signature', models.FileField(upload_to='signatures/')),
                ('business_currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_details', models.TextField(blank=True, default=None)),
                ('caption', models.CharField(blank=True, default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
