from enum import Enum


class NumberConstructorConstants(Enum):
    ASSET_NUMBERING = 'ASSET_NUMBERING'
    VENDOR_NUMBERING = 'VENDOR_NUMBERING'
    PURCHASE_ORDER_NUMBERING = 'PURCHASE_ORDER_NUMBERING'
    GRN_NUMBERING = 'GRN_NUMBERING'
    EMPLOYEE_NUMBERING = 'EMPLOYEE_NUMBERING'
    CATEGORY_NUMBERING = 'CATEGORY_NUMBERING'
    SUBCATEGORY_NUMBERING = 'SUBCATEGORY_NUMBERING'
    BATCH_NUMBERING = 'BATCH_NUMBERING'
