# Generated by Django 5.0.6 on 2024-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbankdetail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bank detail', 'verbose_name_plural': 'historical bank details'},
        ),
        migrations.AlterModelOptions(
            name='historicaldepartment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical department', 'verbose_name_plural': 'historical departments'},
        ),
        migrations.AlterModelOptions(
            name='historicaldesignation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical designation', 'verbose_name_plural': 'historical designations'},
        ),
        migrations.AlterModelOptions(
            name='historicalemployeemaster',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical employee master', 'verbose_name_plural': 'historical employee masters'},
        ),
        migrations.AlterModelOptions(
            name='historicalpocdetail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical poc detail', 'verbose_name_plural': 'historical poc details'},
        ),
        migrations.AlterModelOptions(
            name='historicalvendormaster',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vendor master', 'verbose_name_plural': 'historical vendor masters'},
        ),
        migrations.AlterField(
            model_name='historicalbankdetail',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldepartment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldesignation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeemaster',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpocdetail',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvendormaster',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
