# Generated by Django 4.1.2 on 2024-05-03 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_manager', '0002_initial'),
        ('purchase', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalgoodsreceiptnoteitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptnote',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptnote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='historicalgoodsreceiptnote',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.vendormaster'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitem',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_asset_details', to='asset_manager.asset'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitem',
            name='grn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='inventory.goodsreceiptnote'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='purchase_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='vendor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.vendormaster'),
        ),
    ]
