# Generated by Django 5.0.6 on 2024-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalgoodsreceiptnote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical goods receipt note', 'verbose_name_plural': 'historical goods receipt notes'},
        ),
        migrations.AlterModelOptions(
            name='historicalgoodsreceiptnoteitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical goods receipt note item', 'verbose_name_plural': 'historical goods receipt note items'},
        ),
        migrations.AlterField(
            model_name='historicalgoodsreceiptnote',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalgoodsreceiptnoteitem',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
