# Generated by Django 4.1.2 on 2024-05-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(blank=True, default=None, to='warehouse.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouses',
            field=models.ManyToManyField(blank=True, default=None, to='warehouse.warehouse'),
        ),
    ]
