# Generated by Django 5.0.6 on 2024-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpurchaseorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical purchase order', 'verbose_name_plural': 'historical purchase orders'},
        ),
        migrations.AlterModelOptions(
            name='historicalpurchaseorderitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical purchase order item', 'verbose_name_plural': 'historical purchase order items'},
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorderitem',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
